@FinanceTracker.Api_HostAddress = https://localhost:7228


POST {{FinanceTracker.Api_HostAddress}}/api/identity/register
Content-type: application/json
{
  "email": "u3@test.com",
  "password": "P@ss123"
}

###

POST {{FinanceTracker.Api_HostAddress}}/api/identity/login
Content-type: application/json
{
  "email": "u2@test.com",
  "password": "P@ss123"
}

###
@token = CfDJ8H3kykSn-ZtIrZ77Ics2TfsRLDWpmtwIK9jVbHrBvFaPNVQdm7UmwqMXW-vOpWSujUX7SLaTiqBZTCUJyJ0FWniRRQNyyDTwsQL6jtz7WN6TwVWgZOrbf3SMkpFh3zlp5VFr27uhwC-tGiBdLAjXlhCEYzHSweZD5pCOLxtGmCsbMRi_VwbG4qY3qvZqEIWwwre_XL9e7TpuRuZ3yYMxzT0HiytlEOqfigLUXMzdBkd-Z1xAL0zd5LspF9OmOlVz0wjt1EVYbhpg0Pcyl9_gRBB9_D6g08XhbXo3ntJyPi7p3f56s3CacOvE4HwcF6ZRkPo55GcZJXwAs19oc1l0wljV-qBeW4wLS67Z3kqg7fCncQEIKPO5b6WFybE84QmGxjbpPoIGS0KSe-Kre-E940szFUne5LDCzdPPUKGyp5U1YqtKq28sPagPFb0PzJjDDg1ckttc-BcquxdltDXiVFb6zDpbliUgbYGTCC3uUsDeE0W9ahf9bDtlLTyHYvLhprIyc81C7CLoKqQQ15MYvUlIIUWuI0OsY36vYy1QmFbuYjUJJPcQJPR2GOBZXQkBtSJEsETbF4fLY9FzYjBMdulZwARUPSndDJXCznSERIPCwYrA2tweWm4s514o64haXzvsOUrzYYlr8uDlMnGNL_G_cikrfYSDgMBcK7031APk
@refreshToken = CfDJ8H3kykSn-ZtIrZ77Ics2TfuHUS5U78MEv3_PbdN_CTNAAi-Ele9E7SYb6fncYkFDeAWvfMzdsnQkVbgf7Y0Cr9lXtzwFQZkcjHprvDUfWtJopqgITtVcCmETYxf0QftGJXmgBMw54cmGB614rX13EhKHY-7zmASwzZWxO1ACXLLQIUebvq01to747ywFjccUktolypeRBGCJW296KxHqQI7aMjcppcBH9ydzcHnInBz-dhUL-QFCIp3WD155LXdpmm_fblnyaz_nZ1rIeUrztIfNq0rCUb4kQgW7zCMKSzA_RHk7jQdXRTwHcA59L2Zjns8n3ejNxXesl_lTtdY2Knj4H0Wie0Zj__c7ubyAJMZMtBt-31nW6PuQvy1dDaz7_1gJ_-imB0HCS2CQFhf34msR1mFQb290poQUKE44J197iBBbpvQ9HC1xxDw9xcyW1J_-cWFXlcqGUUfzpUZ7KAAZcovFSEw0Lk38ibY5pLTcFdvUZ-zKimfy9i-JzHiQ5DpZqnJrEzmH8ofQPws1NbfZqES8XkqBVCUx53YzJpz0bTBCudHRWyvVaiSJbyWqyM1nry6EzV-lH7uU65ilSuFJ6oVpTzBfwWLmpIL5vbdzliyE7DOWa3gIpNvIwgDNW89tircPgH8VRQRbZdEbFFVAbT5or7d33_YiNGEn9Vez


POST {{FinanceTracker.Api_HostAddress}}/api/identity/refresh
Content-type: application/json
{
  "refreshToken": "{{refreshToken}}"
}

###

POST {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Akash",
  "Type": "MFS",
  "Currency": "BDT"
}

###

GET {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}

###

@id = 3
GET {{FinanceTracker.Api_HostAddress}}/api/wallets/{{id}}
Authorization: Bearer {{token}}

###

PATCH {{FinanceTracker.Api_HostAddress}}/api/wallets/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Baki",
  "Type": "Cash",
  "Currency": "BDT"
}

###
DELETE {{FinanceTracker.Api_HostAddress}}/api/wallets/{{id}}
Authorization: Bearer {{token}}

###

