@FinanceTracker.Api_HostAddress = https://localhost:7228


POST {{FinanceTracker.Api_HostAddress}}/api/identity/register
Content-type: application/json
{
  "email": "u3@test.com",
  "password": "P@ss123"
}

###

POST {{FinanceTracker.Api_HostAddress}}/api/identity/login
Content-type: application/json
{
  "email": "u2@test.com",
  "password": "P@ss123"
}

###
@token = CfDJ8H3kykSn-ZtIrZ77Ics2Tfsaa6WXix1KAW9iQ3Xi0vCszhe2vpGAtI8jYXjRxJJs4aRaCnleWKlzXtKvUZQGl3EtvVVR-ONKwJMBDPkEO-Wnd3SVOmiKWwuWDbT1DBf241bxoBj3jlNop6vJ0NraYZgrcnucc43Eqpt324LTAVCfwjh3VVfZxICYNGJBiKLc88GwARVSitzpG6loIxf-63u31dXiKzrZCLrSVoNpuyV9f2Z_anAXTYmRPeAiG8QdfVXBTXZd52Dg6Xg_ZNOlOUjtke2F6qlF95yHvfHLVxrk77KQaEUcfdHTfII6ob2VH9OSQ1FvmdvD2uE2SG5avxi_XoDWUS0DSBTS4t9OK0yw3MeIgYVHqE6l3KX6ONNZDWs0c9b3eFqiO6_5MaoU4cmI79TrhFvPJrRRtQaZvOeAL93hvlMl7HSlyS_ZU5t2e7Tg8MUiJ5m_fL2FdHTKwANEYORtYDTtI_wx28DivKcXPrEiI-DPwJIIcg9erZ6Wxyf7BATwj3DMNm1ohIeKtbGxPknudK_9XMGdxym2R5uPaofANH082wrDEIVIXZOeI-mqbDcZB79ioVxTvfO5nbwAnjSStF-ukSHAUvgTiozbR3p2WC1VRXFYxJrzAl-T8kdsvNnRCuV8uxz23keuB5md5GWXuGQAPnRrbxHPWUvt
@refreshToken = CfDJ8H3kykSn-ZtIrZ77Ics2Tfv7lk75k8te3GB-ADCcVsZhXCdlzKqcC1aZP2K9skxIaldbatrEfaUGa8wcHdVOtLqf_vsEBT2NLM9qr64LlckOE-YzB18UR2sE2dmsq28fQG0AYyUlIM36DpeaL3Mw6tofuOpjX-jSE8FTRddcmtHezXyVx-QzFIQWOZBU9L-uPpjzFJDEA02ndca7jnxiOGLbsPXhZOWjFL0l_5MK4tSV401RnmRgEON6htSygGVFWikaq3ZwKtX-WSiQ7peZFZuYsXzmCMm1JEX42vcvIiNB93pez4aldbGYiiaVyPpKo-FOn0KjJZrVQ1zYouC3WShQfv6KO_B6VzUzTYshsVND1mqljTOfrP0Jc5MPjPlO_GOVNZcyV7bSvijIsZyz8WoGQB5L310nps_7urp4W-9_-Y3OZlUDImcRjCMTFG110I1ihqgplfQ7mN8JY6bLo6Em2Qz2vYH-lSzCfCbNDOLEtH7iUP_096dDAEtLzRwGNKhFL-Sc9d5mxCZivwTTlG5icrxFIvrB-kRi9v0veYD0P6QGLZcAecPtNqmQIgUR4rovhK-fubwan5-pVZ-TOMq1TKBdB6VX8fGKdmxC9dxZj5wWSn675JByBopVdsUGAQulLa6klHCqBo02EVnrc7UGkBl9kIjoE1EXw-0ZeJsB


POST {{FinanceTracker.Api_HostAddress}}/api/identity/refresh
Content-type: application/json
{
  "refreshToken": "{{refreshToken}}"
}

###


GET {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}

###

@id = 0
GET {{FinanceTracker.Api_HostAddress}}/api/wallets/{{id}}
Authorization: Bearer {{token}}

###

POST {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Akash",
  "Type": "MFS",
  "Currency": "BDT"
}

###

