@FinanceTracker.Api_HostAddress = https://localhost:7228


POST {{FinanceTracker.Api_HostAddress}}/api/identity/register
Content-type: application/json
{
  "email": "u3@test.com",
  "password": "P@ss123"
}

###

POST {{FinanceTracker.Api_HostAddress}}/api/identity/login
Content-type: application/json
{
  "email": "u2@test.com",
  "password": "P@ss123"
}

###
@token = CfDJ8H3kykSn-ZtIrZ77Ics2TfuNOXOn9aNfLqKfOwcsoSh_cr1tPZ8eHQpWsoAkRMu9h4vBmnD_5Zuwb4Bv0JdxopVL08OJe9SCbIuQts8cWcz2u4OaZQOEl0Cb1k3DTsyPQ85ZDEnH8h1BwQMKAhYXHVYQy8P2zidaIOGj47JfwRxqU6A07cIaPbHZRbUqNFpvDfcUQPkGcOnetACGOdvCCFTD1efqh-U_-6wp0Oryd2aDoCgtsVaf-B-7wo_SJFA6FYKZ1lyXwbmxiBxm2q9bPdIZivR7aY--Y2q5y3bD_loN5K1FDmZPlnQIMC8HgY_22_tzGcZCb3V_BgArnz73kKtS3II9PmShY4JqSghmxMwlglyDypMmVQcMpYiCZJJj32EnR1f13RXBwarC1WqKj2Jcmf1qsdv5c9GZIua7b28QT0idHi6Ru9vegVIh-5pqY01Oia46lSHRCszbNbuDY-fVKHhXEuYJTifZFFCk9OH2WsiG17XaP_7AiCSFzF952a8iZKnOChUEdfALqxVbincImRd5_z9YUQDnt82tfa-xJoEGmIie5JzvbYiVI3Iy8gsKg2YxPgrpPXrpjFVAlFe03s2DBbxB3hz_QmZFBugavdpqxGsi_NI-jdUfipmN8coAXTJqWcsrMTqbVuFwAi2-T3zKZzv7bmtdNZxocGHs
@refreshToken = CfDJ8H3kykSn-ZtIrZ77Ics2TfufuOzPT9KGP57QXi0q4Pfi_RlBKqp9H-O92W5LXOzotmGMAgtRRAzDWHf-RUt7t_0tWQ6X7hr6KDa6xOjdrHEob8a11JetQvJEiURYACQtr3lGv_opK2o4gO9JK-lceCvrf0GfVBN4QSStsw4m4Kikmrr-jVJgjphUl1HUC4HtZVj-PPWveejzLL3aSmhWqOgRs0j4xxi-khcc3pp3TKFZGZdRHk1-rCJOU_d0-Ey1EPIFpPjhxpNgy7rNXEJ-bNOLoW9DD5VOjd6KXMHEh9sbyZ_I0nR_T3zIaNSZdK2bYoQZm1SjGjJq355zuxBP4xYyDAfCCsRkM_uKt7yGus-weCYTaHOw2RAKgA91CzZ_R63c_xTjR2W6ShzTUZjU_gMhEGVNNM1lxQ-nYInjJ9VfsCZrVo__HtrK_w-41dV9m4jNZdDQoWukhabiV2hQa9n3nAcV0z6CKid9fn3teytFvGBqZjQzddVnZMFsH9HNXRY007Ixl6jCVZZYVBV7EdQ9tTl5L27GaXNibHuezx3iakxGj-l7t4_MUTSiupJTFyKoouznlBBKWvURLADXnkvMUh0odUqghBZ7GDy432ne9LebXEsXl7ZKs1L714ySAkARJnSdsq7EixfAlAEPBa2mtz1hmlxJw_hrOTmwL7fw


POST {{FinanceTracker.Api_HostAddress}}/api/identity/refresh
Content-type: application/json
{
  "refreshToken": "{{refreshToken}}"
}

###


GET {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}

###

@id = 0
GET {{FinanceTracker.Api_HostAddress}}/api/wallets/{{id}}
Authorization: Bearer {{token}}

###

POST {{FinanceTracker.Api_HostAddress}}/api/wallets
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Akash",
  "Type": "MFS",
  "Currency": "BDT"
}

###

